FROM ctf/eth_challenge_base:latest

COPY deploy/ /home/ctf/
ENV FLAG X-MAS{Th1s_goes_0n_and_on_and_on_and_on_and_on_and_on_and_on_and_on_and_on_and_on_and_on}
RUN python3 -m pip install -r /home/ctf/requirements.txt 
